// Centralized constants for editor components
// Use these for all magic numbers and strings in the editor

export const DEFAULTS = {
  POSITION: { x: 0, y: 0 },
  SIZE: { width: 100, height: 100 },
  ROTATION: 0,
  FONT_SIZE: 16,
  BORDER_WIDTH: 0,
  BORDER_COLOR: '#888888',
  BORDER_RADIUS: 0,
  CANVAS_BORDER_RADIUS: 12,
  BORDER_STYLE_SOLID: 'solid',
  BORDER_STYLE_NONE: 'none',
  BACKGROUND: 'transparent',
  BACKGROUND_RECT: '#eeeeee',
  BACKGROUND_IMAGE: '#ffffff',
  BACKGROUND_TEXT: '#ffffff',
  TEXT_COLOR: '#000000',
  PLACEHOLDER_IMAGE: 'https://via.placeholder.com/120x80',
  IMAGE_MAX: 400,
  LINE_HEIGHT: 'normal',
  TEXT_ALIGN: 'left',
  CANVAS_MAX_W: 1000,
  CANVAS_MAX_H: 700,
  CANVAS_MIN_W: 300,
  CANVAS_MIN_H: 200,
  CANVAS_MAX_WIDTH: '100%',
  CANVAS_MAX_HEIGHT: '70vh',
  CANVAS_MARGIN: '1rem auto',
  CANVAS_BOX_SIZING: 'border-box',
  CANVAS_TRANSITION: 'width 0.2s, height 0.2s',
  CANVAS_DISPLAY: 'block',
  CANVAS_OVERFLOW: 'hidden',
  CANVAS_POSITION: 'relative',
  CANVAS_BG: '#fff',
  CANVAS_BORDER: '0px solid #888888',
  Z_INDEX_DEFAULT: 0,
  Z_INDEX_STEP: 1,
  ELLIPSE_RADIUS: 60,
  RECT_HEIGHT: 60,
  LINE_HEIGHT_PX: 4,
  IMAGE_HEIGHT: 80,
  IMAGE_WIDTH: 120,
  TEXT_HEIGHT: 40,
  PROJECT_NAME: 'Untitled Project',
  ASPECT_RATIO: '16:9',
  ASPECT_RATIO_16_9: '16:9',
  ASPECT_RATIO_4_3: '4:3',
  WAVE_DECORATION: 'underline wavy',
  SHADOW: '2px 2px 4px #000',
  GLOW: '0 0 8px #00f, 0 0 16px #00f',
  BUTTON_CLASS: 'btn btn-light btn-sm',
  BUTTON_OUTLINE: 'btn btn-sm btn-outline-secondary',
  BUTTON_ACTIVE: ' active',
  FORM_LABEL: 'form-label',
  FORM_GROUP: 'form-group mb-2',
  FORM_CONTROL_COLOR: 'form-control form-control-color',
  FORM_CONTROL_SM: 'form-control form-control-sm',
  FORM_CHECK_INPUT: 'form-check-input',
  FORM_CHECK_LABEL: 'form-check-label',
  LAYERING_CONTROLS: 'layering-controls d-flex gap-1 mb-2',
  EDITOR_ELEMENT: 'editor-element',
  EDITOR_ELEMENT_SELECTED: ' selected',
  EDITOR_IMAGE_SELECTABLE: 'editor-image-selectable',
  EDITOR_CANVAS: 'editor-canvas',
  EDITOR_CANVAS_CONTAINER: 'editor-canvas-container bg-light',
  EDITOR_CANVAS_ZOOM_WRAPPER: 'editor-canvas-zoom-wrapper',
  EDITOR_ROOT: 'editor-root',
  EDITOR_MAIN: 'editor-main',
  PROJECT_NAME_INPUT: 'project-name-input',
  // Default border-radius for ellipse: 50% = true oval/circle shape
  ELLIPSE_BORDER_RADIUS_PCT: 50,
  // Arrow key nudge steps
  ARROW_MOVE_STEP: 1,            // px per tick (plain arrow)
  ARROW_MOVE_STEP_LARGE: 10,    // px per tick (Shift+arrow, overrides acceleration)
  ARROW_MOVE_STEP_ACCEL: 5,     // px per tick after hold threshold
  ARROW_HOLD_ACCEL_DELAY: 500,  // ms of continuous hold before step size increases
};

export const ACTIONS = {
  SET_PROJECT_NAME: 'SET_PROJECT_NAME',
  SET_ASPECT_RATIO: 'SET_ASPECT_RATIO',
  UPDATE_PAGE_BACKGROUND: 'UPDATE_PAGE_BACKGROUND',
  UPDATE_PAGE_BORDER: 'UPDATE_PAGE_BORDER',
  ADD_ELEMENT: 'ADD_ELEMENT',
  UPDATE_ELEMENT: 'UPDATE_ELEMENT',
  DELETE_ELEMENT: 'DELETE_ELEMENT',
  SET_ELEMENTS: 'SET_ELEMENTS',
  SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
  ADD_PAGE: 'ADD_PAGE',
  REMOVE_PAGE: 'REMOVE_PAGE',
  SET_ZOOM: 'SET_ZOOM',
  UNDO: 'UNDO',
  REDO: 'REDO',
  LOAD_STATE: 'LOAD_STATE',
  SELECT_ELEMENT: 'SELECT_ELEMENT',
  DESELECT_ELEMENT: 'DESELECT_ELEMENT',
  BRING_ELEMENT_TO_FRONT: 'BRING_ELEMENT_TO_FRONT',
  SEND_ELEMENT_TO_BACK: 'SEND_ELEMENT_TO_BACK',
  BRING_ELEMENT_FORWARD: 'BRING_ELEMENT_FORWARD',
  SEND_ELEMENT_BACKWARD: 'SEND_ELEMENT_BACKWARD',
};
