//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RST.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RSTResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RSTResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RST.Web.Resources.RSTResource", typeof(RSTResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or Phone is required..
        /// </summary>
        public static string EmailPhoneRequired {
            get {
                return ResourceManager.GetString("EmailPhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailTxt {
            get {
                return ResourceManager.GetString("EmailTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter OTP.
        /// </summary>
        public static string EnterOTPTxt {
            get {
                return ResourceManager.GetString("EnterOTPTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have exhausted all login attempts..
        /// </summary>
        public static string ExhaustedLoginAttempt {
            get {
                return ResourceManager.GetString("ExhaustedLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate OTP.
        /// </summary>
        public static string GenerateOTPTxt {
            get {
                return ResourceManager.GetString("GenerateOTPTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Profile.
        /// </summary>
        public static string GoToProfileTxt {
            get {
                return ResourceManager.GetString("GoToProfileTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already logged in..
        /// </summary>
        public static string LoggedInNowTxt {
            get {
                return ResourceManager.GetString("LoggedInNowTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are logged in..
        /// </summary>
        public static string LoggedInTxt {
            get {
                return ResourceManager.GetString("LoggedInTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginTxt {
            get {
                return ResourceManager.GetString("LoginTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LogoutTxt {
            get {
                return ResourceManager.GetString("LogoutTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string OrTxt {
            get {
                return ResourceManager.GetString("OrTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string PhoneTxt {
            get {
                return ResourceManager.GetString("PhoneTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for free account..
        /// </summary>
        public static string RegisterFreeTxt {
            get {
                return ResourceManager.GetString("RegisterFreeTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Now.
        /// </summary>
        public static string RegisterNowTxt {
            get {
                return ResourceManager.GetString("RegisterNowTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend OTP.
        /// </summary>
        public static string ResendOTPTxt {
            get {
                return ResourceManager.GetString("ResendOTPTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignInTxt {
            get {
                return ResourceManager.GetString("SignInTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to send email..
        /// </summary>
        public static string UnabletoSendEmail {
            get {
                return ResourceManager.GetString("UnabletoSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to send SMS..
        /// </summary>
        public static string Unabletosendsms {
            get {
                return ResourceManager.GetString("Unabletosendsms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to validate credentials..
        /// </summary>
        public static string Unabletovalidatecreds {
            get {
                return ResourceManager.GetString("Unabletovalidatecreds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email or phone is not registered, please register now..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will be redirected now..
        /// </summary>
        public static string YouWillBeRedirectedTxt {
            get {
                return ResourceManager.GetString("YouWillBeRedirectedTxt", resourceCulture);
            }
        }
    }
}
